### ISSUE TITLE
grpc-app sample does not build

### ISSUE THREAD

**Issue by Lipen** [Kotlin/kotlinx-rpc#344]
## Description
The sample project `samples/grpc-app` fails to build due to missing `grpc` plugin-settings-block (I am not sure how to call it):
```kotlin
rpc {
    grpc {  // <== Unresolved reference: grpc
        enabled = true
    }
}
```

<details>
  <summary>Gradle log</summary>

```
> Configure project :
e: file:///.../kotlinx-rpc/samples/grpc-app/build.gradle.kts:31:5: Unresolved reference: grpc
e: file:///.../kotlinx-rpc/samples/grpc-app/build.gradle.kts:32:9: Unresolved reference: enabled

FAILURE: Build failed with an exception.

* Where:
Build file '.../kotlinx-rpc/samples/grpc-app/build.gradle.kts' line: 31

* What went wrong:
Script compilation errors:

  Line 31:     grpc {
               ^ Unresolved reference: grpc

  Line 32:         enabled = true
                   ^ Unresolved reference: enabled

2 errors
```

</details>

This can be "fixed" by using `id("org.jetbrains.kotlinx.rpc.plugin") version "0.5.1-grpc-16"` plugin version instead of `0.6.0` for this particular sample project. Seems like the plugin version was bumped to `0.6.0` in https://github.com/Kotlin/kotlinx-rpc/pull/320. However, `kotlinx-rpc` project does not include `samples/*` in the build (I even had to open this sample project in a separate IDEA, since it didn't load correctly in the root one), so the CI didn't caught that this sample does not build with `0.6.0` plugin anymore.

## To Reproduce
1. Open `samples/grpc-app` as IDEA project.
2. Try to load the Gradle configuration or build the project
3. Error: `Unresolved reference: grpc`

## Expected behavior
- All sample projects *should* run as they are, out of the box. 
- All samples probably *should* be included in the root project.
- All samples *should* be tested on CI.
- All samples *should* be promptly updated to the latest `kotlinx-rpc` plugin version (`0.7.0` at that time) on each release, and all major changes in the user API (like customization via `rpc {}` block) _should_ be mentioned in the `CHANGELOG.md`.

**Comment by Mr3zee** [comment]
Hey! Thanks for the report and sorry for the long answer. I'll take a look at the issue

**Comment by Mr3zee** [comment]
@Lipen @RaySmith-ttc should be alright now
